### ISSUE TITLE
Missing Journal Information in Article Json Response Class

### ISSUE THREAD

**Issue by vishalkr07** [oacore/oacore4j#8]
[Article.java](https://github.com/oacore/oacore4j/blob/master/src/main/java/uk/ac/core/oacore4j/journals/response/Journal.java) class does not contain any member variable for Journal Information. 
Articles search query: 

`repository.id:645`
It return the data containg Jornal details. Please update the class definition.

**Comment by giorgiobasile** [comment]
Thanks for your help, should be fixed in few hours. Btw, did you check whether the journals are included in the `additionalProperties` map of the `Article` object?

**Comment by giorgiobasile** [comment]
Done, please be aware that POJOs have the `additionalProperties` field that parses any additional JSON object not mapped with any of the specified attributes.
